### ISSUE TITLE
請問有實際上使用 DDD 的 Python 專案參考嗎?

### ISSUE THREAD

**Issue by BbsonLin** [ddd-tw/py-ddd-common#1]
哈囉 小弟最近正在拜讀 DDD，但看到的書(小藍書或小紅書)跟範例大多都是 Java 或 C#。

請問有實際上使用 DDD 的 Python 專案範例，可供小弟學習參考的嗎?
感謝~

p.s. 雖然知道軟體設計沒有絕對的答案，但實際上要實行 DDD 還是有點困難阿... 😵

**Comment by kokokuo** [comment]
Hi @BbsonLin 
我是 Eason，我手上有一些專案的範例，可以交流，但由於目前落實居多的多為公司中的專案，所以不方便公開。

很歡迎來到社群目前的 Legacy Code 讀書會或是後續的 Meetup 一起交流。

若往後有時間，我也會另外安排編寫 Side Project 或是開一場  Talk 分享  :) 

若你有興趣，也可以先去看這個專案 https://github.com/kokokuo/meteor
是我原本想要拿來製作的 DDD + sartlette 非同步框架的 scaffold 專案，但才剛起步沒多久 （只有工作中應用)。

**Comment by BbsonLin** [comment]
Hi, @kokokuo 
感謝你的回覆。
目前已加入 ddd-tw FB 社團了，期待讀書會和 Meetup 以及之後的 Talk。
https://github.com/kokokuo/meteor 我先看一下，若有問題會再留 issue 給您。
